name: Prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Run Prettier on Front
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run front-prettify

      - name: Check if changes are present
        id: git-check
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes
        if: steps.git-check.outputs.result == 'Changes detected'
        run: |
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git add .
          git commit -m "Auto-format code with Prettier"
          git push